name: Test & Publish

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Node ${{ matrix.node }} 
    strategy: 
      matrix:
        node-version: [14.x, 16.x] 
    
    services:
      clickhouse:
        image: yandex/clickhouse-server
        ports:
          - 8123:8123

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Verify Clickhouse is Running
        run: curl -v "http://127.0.0.1:8123/"

      - run: yarn install --frozen-lockfile
      - run: yarn test
        env:
          CLICKHOUSE_USER: "default"
          CLICKHOUSE_PASSWORD: ""

  publish:
    name: Release
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' }}

    steps:
      # Checkout
      - uses: actions/checkout@v2
      # NPM Registry
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          scope: ${{ secrets.NPM_MAKEOMATIC_SCOPE }}
      - run: yarn install --frozen-lockfile
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_NPM_TOKEN }}
